# Revision computations — PSCV + ESM-2 autophagy paper

Run the cells in order. Nothing is retrained from scratch: the scripts reuse the
classifiers and predictions already saved in `pscv_work`.

**Before you start**, put the six `.py` files in one Google Drive folder, e.g.
`MyDrive/pscv_code/`:

```
pscv_common.py            (shared definitions — the others import it)
05_statistical_tests.py   DeLong + McNemar
06_ablation.py            feature-group ablation (Table 5)
07_shap_analysis.py       SHAP (Figures 17-19)
08_decision_boundary.py   UMAP decision landscapes (Figures 14-16)
09_external_benchmark.py  external benchmark (optional)
```

For a GPU: **Runtime → Change runtime type → T4 GPU**. Scripts 05 and 06 also work on CPU.

## 1. Mount Google Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os, glob

hits = glob.glob('/content/drive/MyDrive/**/pscv_common.py', recursive=True)

if hits:
    CODE_DIR = os.path.dirname(hits[0])
    os.chdir(CODE_DIR)
    print('Found the scripts in:', CODE_DIR)
    print('Files:', sorted(f for f in os.listdir(CODE_DIR) if f.endswith('.py')))
else:
    print('Not found under MyDrive. Check that the .py files were unzipped and uploaded,')
    print('or use the upload cell below instead.')
    print('\nFolders directly under MyDrive:')
    for d in sorted(os.listdir('/content/drive/MyDrive'))[:40]:
        print('  ', d)

Found the scripts in: /content/drive/MyDrive/pscv_code
Files: ['05_statistical_tests.py', '06_ablation.py', '07_shap_analysis.py', '08_decision_boundary.py', '09_external_benchmark.py', 'pscv_common.py']

## 2. Set the two folder paths

`CODE_DIR` = where you put the `.py` files.
`WORK_DIR` = your existing `pscv_work` folder (the one holding `results.pkl`,
`features.npz` and the `clf_*.pkl` checkpoints).

In [3]:
import os

CODE_DIR = '/content/drive/MyDrive/pscv_code'
WORK_DIR = '/content/drive/MyDrive/pscv_work'

os.chdir(CODE_DIR)          # scripts import pscv_common.py from here
print('code files :', sorted(f for f in os.listdir(CODE_DIR) if f.endswith('.py')))
print('work files :', sorted(os.listdir(WORK_DIR))[:12])

code files : ['05_statistical_tests.py', '06_ablation.py', '07_shap_analysis.py', '08_decision_boundary.py', '09_external_benchmark.py', 'pscv_common.py']
work files : ['clf_BayesianMLP_independent.pkl', 'clf_BlockMoE_independent.pkl', 'clf_CNN-BiLSTM_independent.pkl', 'clf_CNN_independent.pkl', 'clf_MLP_independent.pkl', 'clf_TabNet_independent.pkl', 'clf_TabResNet_independent.pkl', 'clf_Transformer_independent.pkl', 'clf_WideDeep_independent.pkl', 'clf_XGBoost_independent.pkl', 'features.npz', 'folds_10.json']

## 3. Install the packages Colab does not ship with

In [4]:
!pip install -q shap umap-learn
import torch, xgboost, sklearn, shap, umap
print('torch', torch.__version__, '| GPU:', torch.cuda.is_available())
print('xgboost', xgboost.__version__, '| sklearn', sklearn.__version__, '| shap', shap.__version__)

torch 2.11.0+cu130 | GPU: True
xgboost 3.4.1 | sklearn 1.6.1 | shap 0.52.0

## 4. DeLong + McNemar tests  (manuscript Section 3.1.2)

Runs in under a minute, CPU is fine. Writes to `WORK_DIR/stats/`.

In [5]:
WD = WORK_DIR
!python 05_statistical_tests.py --work_dir "{WD}"

AUC (DeLong 95% CI) and ACC (Wilson 95% CI)
       model    n    AUC  AUC_SE  AUC_lo  AUC_hi    ACC  ACC_lo  ACC_hi
   BlockMoE 4684 0.8980  0.0045  0.8892  0.9068 0.8177  0.8064  0.8285
    XGBoost 4684 0.8962  0.0045  0.8873  0.9050 0.8151  0.8037  0.8260
   WideDeep 4684 0.8953  0.0045  0.8864  0.9041 0.8106  0.7992  0.8216
        MLP 4684 0.8950  0.0046  0.8859  0.9040 0.8198  0.8085  0.8306
        CNN 4684 0.8929  0.0047  0.8838  0.9020 0.8177  0.8064  0.8285
BayesianMLP 4684 0.8893  0.0047  0.8801  0.8984 0.8076  0.7961  0.8187

Pairwise DeLong test
  model_A     model_B  AUC_A  AUC_B   dAUC      z      p  p_holm
BlockMoE     XGBoost 0.8980 0.8962 0.0018 0.6094 0.5422  1.0000
BlockMoE    WideDeep 0.8980 0.8953 0.0028 1.1011 0.2709  1.0000
BlockMoE         MLP 0.8980 0.8950 0.0031 1.2213 0.2220  1.0000
BlockMoE         CNN 0.8980 0.8929 0.0051 1.6391 0.1012  1.0000
BlockMoE BayesianMLP 0.8980 0.8893 0.0087 3.1455 0.0017  0.0249
 XGBoost    WideDeep 0.8962 0.8953 0.0009 0.3050 0.7603  1.0000
 XGBoost         MLP 0.8962 0.8950 0.0012 0.3658 0.7145  1.0000
 XGBoost         CNN 0.8962 0.8929 0.0033 1.1144 0.2651  1.0000
 XGBoost BayesianMLP 0.8962 0.8893 0.0069 2.0283 0.0425  0.5360
WideDeep         MLP 0.8953 0.8950 0.0003 0.1182 0.9059  1.0000
WideDeep         CNN 0.8953 0.8929 0.0024 0.7292 0.4659  1.0000
WideDeep BayesianMLP 0.8953 0.8893 0.0060 2.3119 0.0208  0.2910
     MLP         CNN 0.8950 0.8929 0.0021 0.6282 0.5299  1.0000
     MLP BayesianMLP 0.8950 0.8893 0.0057 2.0412 0.0412  0.5360
     CNN BayesianMLP 0.8929 0.8893 0.0036 1.0264 0.3047  1.0000

Pairwise McNemar test
  model_A     model_B  A_right_B_wrong  A_wrong_B_right  chi2_cc  p_chi2  p_exact  p_holm
BlockMoE     XGBoost              306              294   0.2017  0.6534   0.6534  1.0000
BlockMoE    WideDeep              263              230   2.0771  0.1495   0.1495  1.0000
BlockMoE         MLP              216              226   0.1833  0.6686   0.6686  1.0000
BlockMoE         CNN              277              277   0.0018  0.9661   1.0000  1.0000
BlockMoE BayesianMLP              315              268   3.6295  0.0568   0.0567  0.7824
 XGBoost    WideDeep              305              284   0.6791  0.4099   0.4099  1.0000
 XGBoost         MLP              293              315   0.7253  0.3944   0.3944  1.0000
 XGBoost         CNN              254              266   0.2327  0.6295   0.6296  1.0000
 XGBoost BayesianMLP              332              297   1.8378  0.1752   0.1752  1.0000
WideDeep         MLP              220              263   3.6522  0.0560   0.0559  0.7824
WideDeep         CNN              283              316   1.7095  0.1910   0.1910  1.0000
WideDeep BayesianMLP              246              232   0.3536  0.5521   0.5522  1.0000
     MLP         CNN              294              284   0.1401  0.7081   0.7082  1.0000
     MLP BayesianMLP              302              245   5.7331  0.0166   0.0166  0.2485
     CNN BayesianMLP              348              301   3.2604  0.0710   0.0709  0.8507

Saved to /content/drive/MyDrive/pscv_work/stats

## 5. Feature-group ablation  (Table 5)

Retrains each classifier on PSCV only / ESM-2 only / fused, five seeds each.
About 25-40 minutes on a T4.

**It is resumable**: every finished run is saved to `WORK_DIR/ablation/ablation_preds.pkl`,
so if Colab disconnects, just run the cell again and it continues where it stopped.

In [6]:
WD = WORK_DIR
!python 06_ablation.py --work_dir "{WD}" --models BlockMoE XGBoost MLP CNN BayesianMLP

BlockMoE     PSCV  seed=42  AUC=0.7627 ACC=0.6904 MCC=0.3826  (31s)
BlockMoE     PSCV  seed=43  AUC=0.7441 ACC=0.6783 MCC=0.3562  (16s)
BlockMoE     PSCV  seed=44  AUC=0.7521 ACC=0.6772 MCC=0.3578  (32s)
BlockMoE     PSCV  seed=45  AUC=0.7518 ACC=0.6857 MCC=0.3712  (19s)
BlockMoE     PSCV  seed=46  AUC=0.7352 ACC=0.6742 MCC=0.3493  (12s)
BlockMoE     ESM2  seed=42  AUC=0.8995 ACC=0.8187 MCC=0.6379  (18s)
BlockMoE     ESM2  seed=43  AUC=0.8980 ACC=0.8183 MCC=0.6373  (13s)
BlockMoE     ESM2  seed=44  AUC=0.8994 ACC=0.8241 MCC=0.6480  (13s)
BlockMoE     ESM2  seed=45  AUC=0.8957 ACC=0.8126 MCC=0.6252  (11s)
BlockMoE     ESM2  seed=46  AUC=0.8931 ACC=0.8072 MCC=0.6142  (9s)
BlockMoE     FUSED seed=42  AUC=0.8991 ACC=0.8134 MCC=0.6268  (29s)
BlockMoE     FUSED seed=43  AUC=0.8971 ACC=0.8117 MCC=0.6246  (21s)
BlockMoE     FUSED seed=44  AUC=0.8944 ACC=0.8057 MCC=0.6119  (20s)
BlockMoE     FUSED seed=45  AUC=0.8982 ACC=0.8160 MCC=0.6319  (13s)
BlockMoE     FUSED seed=46  AUC=0.8958 ACC=0.8106 MCC=0.6210  (11s)
XGBoost      PSCV  seed=0  AUC=0.7683 ACC=0.6983 MCC=0.3963  (8s)
XGBoost      ESM2  seed=0  AUC=0.8979 ACC=0.8147 MCC=0.6295  (273s)
XGBoost      FUSED seed=0  AUC=0.8957 ACC=0.8098 MCC=0.6197  (247s)
MLP          PSCV  seed=42  AUC=0.7545 ACC=0.6874 MCC=0.3742  (31s)
MLP          PSCV  seed=43  AUC=0.7585 ACC=0.6889 MCC=0.3773  (31s)
MLP          PSCV  seed=44  AUC=0.7457 ACC=0.6834 MCC=0.3661  (18s)
MLP          PSCV  seed=45  AUC=0.7374 ACC=0.6768 MCC=0.3551  (10s)
MLP          PSCV  seed=46  AUC=0.7439 ACC=0.6774 MCC=0.3542  (24s)
MLP          ESM2  seed=42  AUC=0.8992 ACC=0.8181 MCC=0.6360  (17s)
MLP          ESM2  seed=43  AUC=0.8923 ACC=0.8134 MCC=0.6267  (13s)
MLP          ESM2  seed=44  AUC=0.8956 ACC=0.8136 MCC=0.6270  (19s)
MLP          ESM2  seed=45  AUC=0.8933 ACC=0.8081 MCC=0.6159  (11s)
MLP          ESM2  seed=46  AUC=0.8942 ACC=0.8079 MCC=0.6154  (10s)
MLP          FUSED seed=42  AUC=0.8955 ACC=0.8192 MCC=0.6381  (19s)
MLP          FUSED seed=43  AUC=0.8977 ACC=0.8207 MCC=0.6413  (18s)
MLP          FUSED seed=44  AUC=0.8928 ACC=0.8119 MCC=0.6236  (14s)
MLP          FUSED seed=45  AUC=0.8964 ACC=0.8168 MCC=0.6335  (16s)
MLP          FUSED seed=46  AUC=0.8927 ACC=0.8198 MCC=0.6394  (26s)
CNN          PSCV  seed=42  AUC=0.7590 ACC=0.6906 MCC=0.3808  (28s)
CNN          PSCV  seed=43  AUC=0.7561 ACC=0.6855 MCC=0.3713  (22s)
CNN          PSCV  seed=44  AUC=0.7575 ACC=0.6866 MCC=0.3727  (44s)
CNN          PSCV  seed=45  AUC=0.7508 ACC=0.6817 MCC=0.3661  (21s)
CNN          PSCV  seed=46  AUC=0.7566 ACC=0.6892 MCC=0.3795  (29s)
CNN          ESM2  seed=42  AUC=0.8966 ACC=0.8132 MCC=0.6262  (44s)
CNN          ESM2  seed=43  AUC=0.8946 ACC=0.8119 MCC=0.6238  (67s)
CNN          ESM2  seed=44  AUC=0.8922 ACC=0.8102 MCC=0.6201  (61s)
CNN          ESM2  seed=45  AUC=0.8934 ACC=0.8074 MCC=0.6149  (52s)
CNN          ESM2  seed=46  AUC=0.8922 ACC=0.8087 MCC=0.6171  (63s)
CNN          FUSED seed=42  AUC=0.8934 ACC=0.8119 MCC=0.6235  (70s)
CNN          FUSED seed=43  AUC=0.8901 ACC=0.8051 MCC=0.6100  (94s)
CNN          FUSED seed=44  AUC=0.8906 ACC=0.8070 MCC=0.6137  (99s)
CNN          FUSED seed=45  AUC=0.8944 ACC=0.8134 MCC=0.6265  (72s)
CNN          FUSED seed=46  AUC=0.8880 ACC=0.8055 MCC=0.6170  (46s)
BayesianMLP  PSCV  seed=42  AUC=0.7588 ACC=0.6857 MCC=0.3709  (26s)
BayesianMLP  PSCV  seed=43  AUC=0.7680 ACC=0.6915 MCC=0.3824  (23s)
BayesianMLP  PSCV  seed=44  AUC=0.7433 ACC=0.6813 MCC=0.3620  (12s)
BayesianMLP  PSCV  seed=45  AUC=0.7574 ACC=0.6813 MCC=0.3618  (19s)
BayesianMLP  PSCV  seed=46  AUC=0.7634 ACC=0.6921 MCC=0.3857  (20s)
BayesianMLP  ESM2  seed=42  AUC=0.8974 ACC=0.8074 MCC=0.6169  (12s)
BayesianMLP  ESM2  seed=43  AUC=0.8948 ACC=0.8119 MCC=0.6236  (12s)
BayesianMLP  ESM2  seed=44  AUC=0.8926 ACC=0.8087 MCC=0.6190  (7s)
BayesianMLP  ESM2  seed=45  AUC=0.8947 ACC=0.8089 MCC=0.6179  (9s)
BayesianMLP  ESM2  seed=46  AUC=0.8939 ACC=0.8158 MCC=0.6313  (17s)
BayesianMLP  FUSED seed=42  AUC=0.8970 ACC=0.8158 MCC=0.6313  (14s)
BayesianMLP  FUSED seed=43  AUC=0.8976 ACC=0.8149 MCC=0.6295  (8s)
BayesianMLP  FUSED seed=44  AUC=0.8933 ACC=0.8134 MCC=0.6267  (11s)
BayesianMLP  FUSED seed=45  AUC=0.9002 ACC=0.8232 MCC=0.6462  (13s)
BayesianMLP  FUSED seed=46  AUC=0.8979 ACC=0.8196 MCC=0.6390  (14s)

       model features  AUC_mean  ACC_mean  MCC_mean  F1_mean  SENS_mean  SPEC_mean  AUC_sd  ACC_sd  MCC_sd  F1_sd  SENS_sd  SPEC_sd  n_runs
BayesianMLP     ESM2    0.8947    0.8105    0.6217   0.8051     0.8029     0.8178  0.0016  0.0030  0.0053 0.0057   0.0271   0.0274       5
BayesianMLP    FUSED    0.8972    0.8174    0.6346   0.8122     0.8094     0.8250  0.0023  0.0036  0.0071 0.0030   0.0052   0.0092       5
BayesianMLP     PSCV    0.7582    0.6864    0.3726   0.6761     0.6717     0.7004  0.0083  0.0047  0.0100 0.0106   0.0252   0.0189       5
   BlockMoE     ESM2    0.8972    0.8162    0.6326   0.8114     0.8110     0.8211  0.0025  0.0058  0.0117 0.0071   0.0199   0.0181       5
   BlockMoE    FUSED    0.8969    0.8115    0.6232   0.8086     0.8163     0.8069  0.0017  0.0034  0.0067 0.0040   0.0134   0.0136       5
   BlockMoE     PSCV    0.7492    0.6812    0.3634   0.6631     0.6453     0.7154  0.0091  0.0060  0.0119 0.0154   0.0475   0.0502       5
        CNN     ESM2    0.8938    0.8103    0.6204   0.8047     0.8011     0.8191  0.0017  0.0021  0.0041 0.0020   0.0091   0.0109       5
        CNN    FUSED    0.8913    0.8086    0.6181   0.7993     0.7827     0.8333  0.0023  0.0034  0.0061 0.0085   0.0313   0.0274       5
        CNN     PSCV    0.7560    0.6867    0.3741   0.6658     0.6414     0.7299  0.0028  0.0031  0.0054 0.0151   0.0405   0.0373       5
        MLP     ESM2    0.8949    0.8122    0.6242   0.8067     0.8031     0.8209  0.0024  0.0039  0.0077 0.0038   0.0060   0.0073       5
        MLP    FUSED    0.8950    0.8177    0.6352   0.8118     0.8064     0.8284  0.0020  0.0032  0.0063 0.0045   0.0111   0.0065       5
        MLP     PSCV    0.7480    0.6828    0.3654   0.6632     0.6409     0.7227  0.0076  0.0050  0.0095 0.0119   0.0262   0.0211       5
    XGBoost     ESM2    0.8979    0.8147    0.6295   0.8049     0.7834     0.8445  0.0000  0.0000  0.0000 0.0000   0.0000   0.0000       1
    XGBoost    FUSED    0.8957    0.8098    0.6197   0.7998     0.7790     0.8391  0.0000  0.0000  0.0000 0.0000   0.0000   0.0000       1
    XGBoost     PSCV    0.7683    0.6983    0.3963   0.6786     0.6530     0.7416  0.0000  0.0000  0.0000 0.0000   0.0000   0.0000       1

       model    comparison  AUC_fused  AUC_single    dAUC       z      p
   BlockMoE FUSED vs PSCV     0.9071      0.7582  0.1489 22.1372 0.0000
   BlockMoE FUSED vs ESM2     0.9071      0.9066  0.0005  0.4111 0.6810
    XGBoost FUSED vs PSCV     0.8957      0.7683  0.1274 20.6395 0.0000
    XGBoost FUSED vs ESM2     0.8957      0.8979 -0.0022 -1.4785 0.1393
        MLP FUSED vs PSCV     0.9047      0.7566  0.1481 21.7271 0.0000
        MLP FUSED vs ESM2     0.9047      0.9055 -0.0008 -0.5309 0.5955
        CNN FUSED vs PSCV     0.9018      0.7681  0.1338 20.8772 0.0000
        CNN FUSED vs ESM2     0.9018      0.9043 -0.0025 -1.5661 0.1173
BayesianMLP FUSED vs PSCV     0.9056      0.7691  0.1365 21.0229 0.0000
BayesianMLP FUSED vs ESM2     0.9056      0.9058 -0.0001 -0.1135 0.9097

## 6. SHAP analysis  (Figures 17-19)

About 5-10 minutes on a T4. Writes figures to `WORK_DIR/plots/shap_v2/` and every
number quoted in the text to `WORK_DIR/shap_v2/shap_summary.json`.

In [7]:
WD = WORK_DIR
!python 07_shap_analysis.py --work_dir "{WD}" --n_background 100 --n_explain 300

/content/drive/MyDrive/pscv_code/pscv_common.py:356: UserWarning: [12:44:30] WARNING: /__w/xgboost/xgboost/src/collective/../data/../common/error_msg.h:83: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  d = _Unpickler(f).load()
XGBoost: PSCV share of total |SHAP| = 2.1%  (best PSCV rank among 1433 features: 88)
MLP: PSCV share of total |SHAP| = 1.6%  (best PSCV rank among 1433 features: 223)
BlockMoE: PSCV share of total |SHAP| = 0.1%  (best PSCV rank among 1433 features: 1281)
saved -> /content/drive/MyDrive/pscv_work/plots/shap_v2 and /content/drive/MyDrive/pscv_work/shap_v2

## 7. Decision landscapes  (Figures 14-16)

The UMAP projection takes a few minutes the first time and is then cached in
`WORK_DIR/umap_projection.npy`, so re-runs are fast. Figures go to
`WORK_DIR/plots/boundary_v2/`.

In [8]:
WD = WORK_DIR
!python 08_decision_boundary.py --work_dir "{WD}"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1791549953.558239   10948 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
/usr/local/lib/python3.13/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
wrote /content/drive/MyDrive/pscv_work/plots/boundary_v2/boundary_BlockMoE.png
/content/drive/MyDrive/pscv_code/pscv_common.py:356: UserWarning: [12:46:37] WARNING: /__w/xgboost/xgboost/src/collective/../data/../common/error_msg.h:83: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  d = _Unpickler(f).load()
wrote /content/drive/MyDrive/pscv_work/plots/boundary_v2/boundary_XGBoost.png
wrote /content/drive/MyDrive/pscv_work/plots/boundary_v2/boundary_MLP.png

## 8. Look at the results

In [9]:
WD = WORK_DIR
import pandas as pd, json, os
pd.set_option('display.width', 200)
pd.set_option('display.float_format', lambda v: f'{v:.4f}')

print('=== AUC with DeLong 95% CI ===')
display(pd.read_csv(f'{WD}/stats/auc_ci_delong.csv'))

print('=== Pairwise DeLong ===')
display(pd.read_csv(f'{WD}/stats/pairwise_delong.csv'))

abl = f'{WD}/ablation/ablation_summary.csv'
if os.path.exists(abl):
    print('=== Ablation (Table 5 / Supplementary Table S4) ===')
    display(pd.read_csv(abl))

shp = f'{WD}/shap_v2/shap_summary.json'
if os.path.exists(shp):
    s = json.load(open(shp))
    for m, v in s['models'].items():
        print(m, '-> PSCV share of total |SHAP|:',
              f"{100*v['share_of_total_abs_shap']['PSCV (153)']:.2f}%",
              '| best PSCV rank of 1433:', v['best_rank_of_a_pscv_feature'])

=== AUC with DeLong 95% CI ===

         model     n    AUC  AUC_SE  AUC_lo  AUC_hi    ACC  ACC_lo  ACC_hi
0     BlockMoE  4684 0.8980  0.0045  0.8892  0.9068 0.8177  0.8064  0.8285
1      XGBoost  4684 0.8962  0.0045  0.8873  0.9050 0.8151  0.8037  0.8260
2     WideDeep  4684 0.8953  0.0045  0.8864  0.9041 0.8106  0.7992  0.8216
3          MLP  4684 0.8950  0.0046  0.8859  0.9040 0.8198  0.8085  0.8306
4          CNN  4684 0.8929  0.0047  0.8838  0.9020 0.8177  0.8064  0.8285
5  BayesianMLP  4684 0.8893  0.0047  0.8801  0.8984 0.8076  0.7961  0.8187

=== Pairwise DeLong ===

     model_A      model_B  AUC_A  AUC_B   dAUC      z      p  p_holm
0   BlockMoE      XGBoost 0.8980 0.8962 0.0018 0.6094 0.5422  1.0000
1   BlockMoE     WideDeep 0.8980 0.8953 0.0028 1.1011 0.2709  1.0000
2   BlockMoE          MLP 0.8980 0.8950 0.0031 1.2213 0.2220  1.0000
3   BlockMoE          CNN 0.8980 0.8929 0.0051 1.6391 0.1012  1.0000
4   BlockMoE  BayesianMLP 0.8980 0.8893 0.0087 3.1455 0.0017  0.0249
5    XGBoost     WideDeep 0.8962 0.8953 0.0009 0.3050 0.7603  1.0000
6    XGBoost          MLP 0.8962 0.8950 0.0012 0.3658 0.7145  1.0000
7    XGBoost          CNN 0.8962 0.8929 0.0033 1.1144 0.2651  1.0000
8    XGBoost  BayesianMLP 0.8962 0.8893 0.0069 2.0283 0.0425  0.5360
9   WideDeep          MLP 0.8953 0.8950 0.0003 0.1182 0.9059  1.0000
10  WideDeep          CNN 0.8953 0.8929 0.0024 0.7292 0.4659  1.0000
11  WideDeep  BayesianMLP 0.8953 0.8893 0.0060 2.3119 0.0208  0.2910
12       MLP          CNN 0.8950 0.8929 0.0021 0.6282 0.5299  1.0000
13       MLP  BayesianMLP 0.8950 0.8893 0.0057 2.0412 0.0412  0.5360
14       CNN  BayesianMLP 0.8929 0.8893 0.0036 1.0264 0.3047  1.0000

=== Ablation (Table 5 / Supplementary Table S4) ===

          model features  AUC_mean  ACC_mean  MCC_mean  F1_mean  SENS_mean  SPEC_mean  AUC_sd  ACC_sd  MCC_sd  F1_sd  SENS_sd  SPEC_sd  n_runs
0   BayesianMLP     ESM2    0.8947    0.8105    0.6217   0.8051     0.8029     0.8178  0.0016  0.0030  0.0053 0.0057   0.0271   0.0274       5
1   BayesianMLP    FUSED    0.8972    0.8174    0.6346   0.8122     0.8094     0.8250  0.0023  0.0036  0.0071 0.0030   0.0052   0.0092       5
2   BayesianMLP     PSCV    0.7582    0.6864    0.3726   0.6761     0.6717     0.7004  0.0083  0.0047  0.0100 0.0106   0.0252   0.0189       5
3      BlockMoE     ESM2    0.8972    0.8162    0.6326   0.8114     0.8110     0.8211  0.0025  0.0058  0.0117 0.0071   0.0199   0.0181       5
4      BlockMoE    FUSED    0.8969    0.8115    0.6232   0.8086     0.8163     0.8069  0.0017  0.0034  0.0067 0.0040   0.0134   0.0136       5
5      BlockMoE     PSCV    0.7492    0.6812    0.3634   0.6631     0.6453     0.7154  0.0091  0.0060  0.0119 0.0154   0.0475   0.0502       5
6           CNN     ESM2    0.8938    0.8103    0.6204   0.8047     0.8011     0.8191  0.0017  0.0021  0.0041 0.0020   0.0091   0.0109       5
7           CNN    FUSED    0.8913    0.8086    0.6181   0.7993     0.7827     0.8333  0.0023  0.0034  0.0061 0.0085   0.0313   0.0274       5
8           CNN     PSCV    0.7560    0.6867    0.3741   0.6658     0.6414     0.7299  0.0028  0.0031  0.0054 0.0151   0.0405   0.0373       5
9           MLP     ESM2    0.8949    0.8122    0.6242   0.8067     0.8031     0.8209  0.0024  0.0039  0.0077 0.0038   0.0060   0.0073       5
10          MLP    FUSED    0.8950    0.8177    0.6352   0.8118     0.8064     0.8284  0.0020  0.0032  0.0063 0.0045   0.0111   0.0065       5
11          MLP     PSCV    0.7480    0.6828    0.3654   0.6632     0.6409     0.7227  0.0076  0.0050  0.0095 0.0119   0.0262   0.0211       5
12      XGBoost     ESM2    0.8979    0.8147    0.6295   0.8049     0.7834     0.8445  0.0000  0.0000  0.0000 0.0000   0.0000   0.0000       1
13      XGBoost    FUSED    0.8957    0.8098    0.6197   0.7998     0.7790     0.8391  0.0000  0.0000  0.0000 0.0000   0.0000   0.0000       1
14      XGBoost     PSCV    0.7683    0.6983    0.3963   0.6786     0.6530     0.7416  0.0000  0.0000  0.0000 0.0000   0.0000   0.0000       1

XGBoost -> PSCV share of total |SHAP|: 2.12% | best PSCV rank of 1433: 88
MLP -> PSCV share of total |SHAP|: 1.61% | best PSCV rank of 1433: 223
BlockMoE -> PSCV share of total |SHAP|: 0.07% | best PSCV rank of 1433: 1281

In [10]:
WD = WORK_DIR
from IPython.display import Image, display
for f in ['plots/boundary_v2/boundary_BlockMoE.png',
          'plots/shap_v2/shap_pscv_BlockMoE.png',
          'plots/shap_v2/shap_blocks_all.png']:
    p = f'{WD}/{f}'
    if os.path.exists(p):
        print(f)
        display(Image(p, width=850))

Output hidden; open in https://colab.research.google.com to view.

## 9. External benchmark (optional — Section 3.4)

The reviewer asked for a head-to-head comparison with a published predictor. Upload the
positive and negative FASTA files of a published benchmark (e.g. the ATGPred-FL /
EnsembleDL-ATG independent test set) and run:

The script removes any external protein whose sequence also appears in your training set,
computes PSCV + ESM-2 features with the same code as notebook 02, and scores the saved
classifiers **without retraining**. Needs a GPU for the ESM-2 step.

In [12]:
WD = WORK_DIR
# !python 09_external_benchmark.py --work_dir "{WD}" \
#         --pos /content/ext_pos.fasta --neg /content/ext_neg.fasta --name ATGPredFL_test